WARNING 2025-05-25 16:33:25,787 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 34 - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 28, in receive
    _ = text_data["message"]
        ~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
WARNING 2025-05-25 16:33:38,407 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 34 - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 28, in receive
    _ = text_data["message"]
        ~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
WARNING 2025-05-25 16:34:10,272 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 34 - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 28, in receive
    _ = text_data["message"]
        ~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
WARNING 2025-05-25 16:34:13,061 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 34 - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 28, in receive
    _ = text_data["message"]
        ~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
CRITICAL 2025-05-25 16:35:12,451 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 28 - <class 'str'>
WARNING 2025-05-25 16:35:12,452 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 36 - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 29, in receive
    _ = text_data["message"]
        ~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
ERROR 2025-05-25 16:35:33,145 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 28 - <class 'str'>
WARNING 2025-05-25 16:35:33,145 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 36 - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 29, in receive
    _ = text_data["message"]
        ~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
ERROR 2025-05-25 16:35:35,905 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 28 - <class 'str'>
WARNING 2025-05-25 16:35:35,906 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 36 - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 29, in receive
    _ = text_data["message"]
        ~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
ERROR 2025-05-25 16:35:43,989 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 28 - <class 'str'>
WARNING 2025-05-25 16:35:43,989 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 36 - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 29, in receive
    _ = text_data["message"]
        ~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
ERROR 2025-05-25 16:35:45,148 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 28 - <class 'str'>
WARNING 2025-05-25 16:35:45,148 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 36 - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 29, in receive
    _ = text_data["message"]
        ~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
ERROR 2025-05-25 16:35:51,180 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 28 - <class 'str'>
WARNING 2025-05-25 16:35:51,181 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 36 - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 29, in receive
    _ = text_data["message"]
        ~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
WARNING 2025-05-25 16:37:20,980 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 37 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 28, in receive
    json_data = json.loads(text_data)
  File "/usr/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/json/decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING 2025-05-25 16:37:43,600 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 37 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 28, in receive
    json_data = json.loads(text_data)
  File "/usr/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/json/decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING 2025-05-25 16:38:30,556 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 37 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 28, in receive
    json_data = json.loads(text_data)
  File "/usr/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/json/decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING 2025-05-25 16:39:07,025 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 38 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 29, in receive
    json_data = json.loads(text_data)
  File "/usr/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/json/decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING 2025-05-25 16:39:36,432 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 38 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 29, in receive
    json_data = json.loads(text_data)
  File "/usr/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/json/decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING 2025-05-25 16:39:38,039 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 38 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 29, in receive
    json_data = json.loads(text_data)
  File "/usr/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/json/decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING 2025-05-25 16:39:39,774 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 38 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 29, in receive
    json_data = json.loads(text_data)
  File "/usr/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/json/decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING 2025-05-25 16:39:50,582 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 38 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 29, in receive
    json_data = json.loads(text_data)
  File "/usr/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/json/decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING 2025-05-25 16:39:52,346 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 38 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 29, in receive
    json_data = json.loads(text_data)
  File "/usr/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/json/decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING 2025-05-25 16:40:31,794 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 38 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 29, in receive
    json_data = json.loads(text_data)
  File "/usr/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/json/decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING 2025-05-25 16:40:51,341 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 38 - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 31, in receive
    _ = text_data["message"]
        ~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
WARNING 2025-05-25 16:40:55,220 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 38 - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 31, in receive
    _ = text_data["message"]
        ~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
WARNING 2025-05-25 16:41:05,353 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 38 - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py", line 31, in receive
    _ = text_data["message"]
        ~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
CRITICAL 2025-05-25 16:41:22,758 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 33 - {
    "message":"ss"
}
CRITICAL 2025-05-25 16:41:31,625 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 33 - {
    "message":"ss"
}
CRITICAL 2025-05-25 16:42:18,675 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 33 - {
    "message":"ss"
}
CRITICAL 2025-05-25 16:42:37,705 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 33 - {
    "message":"ss"
}
CRITICAL 2025-05-25 16:42:38,334 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 33 - {
    "message":"ss"
}
CRITICAL 2025-05-25 16:42:39,613 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 33 - {
    "message":"ss"
}
CRITICAL 2025-05-25 16:47:42,325 /home/ali/Desktop/Django/ChatBox/src/private_module/consumers.py consumers 30 - sSSSSSSSSSs ss
